### PR TITLE
Lack of uri encoding on file paths can cause errors on download calls

### PR DESCRIPTION
**Pull request by AndrewCEmil**

### CODE REVIEW

**Comment by AndrewCEmil** [comment]
Reviewing the code I have a much better method for doing this and will update with a new pull request

**Comment by mstramel** [comment]
Andrew - I'd like to speak with you about your ideas and plans for the Egnyte Ruby client? Can you send me an email so we can connect? mstramel at egnyte.com

Thanks

**Comment by pfeffed** [comment]
Andrew,

Sorry there was a crossed wire between teams on our side.  I filled Stramel in regarding the work you're doing.  Thanks for the PR.  I'll try to review it later today. 

Regards,

**Comment by AndrewCEmil** [comment]
No problem, lets not merge in this PR as I have a more general approach and will be opening a PR for that soon.

**Comment by egnyte-api** [comment]
Okay, will stand by.


David Pfeffer
1350 W. Middlefield Road | Mountain View, CA 94043 | USA
W: +1.650.980.4152 | M: +1.202.329.3557 | E: dpfeffer@egnyte.com

**Pull request closed without merging**
